version: '3'
services:
  batch-mongodb:
    container_name: batch-mongodb
    image: mongo:3.4
    volumes:
      - ./_data:/data/db
    ports:
      - 12345:27017
      - 23456:28017
    command: ["mongod", "--rest"]

  batch-app:
    container_name: batch-app
    image: batch-app
    build: Dockerfile
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://localhost:27017/fiap
      - MONGODB_STATUS_HOST=localhost/
      - MONGODB_STATUS_PORT=27017
    ports:
      - "8080:8080"
    depends_on:
      - batch-mongodb