version: '3'
services:
  fiap-mongodb:
    container_name: fiap-mongodb
    image: mongo:3.4
    volumes:
      - ./_data:/data/db
    ports:
      - 12345:27017
      - 23456:28017
    command: ["mongod", "--rest"]

  fiap-app:
    container_name: fiap-app
    image: fiap-app
    build: ./app
    environment:
      - SERVER_PORT=3000
      - MONGODB_URI=mongodb://fiap-mongodb:27017/fiap
      - MONGODB_STATUS_HOST=fiap-mongodb
      - MONGODB_STATUS_PORT=28017
    ports:
      - "3000:3000"
      - "5050:5050"
    depends_on:
      - fiap-mongodb

  fiap-api:
    container_name: fiap-api
    image: fiap-api
    build: ./api
    environment:
      - SERVER_PORT=5000
      - MONGODB_URI=mongodb://fiap-mongodb:27017/fiap
      - MONGODB_STATUS_HOST=fiap-mongodb
      - MONGODB_STATUS_PORT=28017
    ports:
      - "5000:5000"
    depends_on:
      - fiap-mongodb