version: '3'
services:
  fiap-mongodb:
    container_name: fiap-mongodb
    image: mongo:3.4
    volumes:
      - ./_data:/data/db
    ports:
      - 12345:27017
      - 23456:28017
    command: ["mongod", "--rest"]

  batch-app:
    container_name: batch-app
    image: batch-app
    build: ./app
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://fiap-mongodb:27017/fiap
      - MONGODB_STATUS_HOST=fiap-mongodb
      - MONGODB_STATUS_PORT=28017
    ports:
      - "8080:8080"
    depends_on:
      - fiap-mongodb